repos:
  - repo: local
    hooks:

      # Code functionality check

      - id: pytest
        name: pytest
        entry: pytest
        language: system
        args: ["--cov", "--cov-fail-under=90", "tests/"]
        types: [python]


      # Code security check

      - id: bandit
        name: bandit
        entry: bandit
        language: system
        args: ["--recursive", "gherkin_processor/"]
        types: [python]


      # Code Linting check

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        args: ["--max-line-length=160", "--fail-under=9.90", "gherkin_processor/"]
        types: [python]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        args: ["--strict", "gherkin_processor/"]
        types: [python]

      # Code Metrics check

      - id: radon-cc
        name: radon cc
        entry: radon cc
        language: system
        args: ["gherkin_processor/"]
        types: [python]

      - id: radon-mi
        name: radon mi
        entry: radon mi
        language: system
        args: ["gherkin_processor/"]
        types: [python]

      # Code Format check
      - id: pycodestyle
        name: pycodestyle
        entry: pycodestyle
        language: system
        args: ["--max-line-length=160", "gherkin_processor/"]
        types: [python]

      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        args: ["gherkin_processor/"]
        types: [python]