name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  Functionality:
    name: Core Functionality
    uses: ./.github/workflows/functionality.yml

  Security:
    name: Project Security
    uses: ./.github/workflows/security.yml

  Quality:
    name: Code Quality
    needs: [Functionality, Security]
    uses: ./.github/workflows/quality.yml

  Format:
    name: Code Format
    needs: [Functionality, Security]
    uses: ./.github/workflows/format.yml