name: Main CI Workflow

on:
  pull_request:
    types:
    - closed
    branches: [$default-branch]


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    
    Test:
      strategy:
        matrix:
          task: [""]
      name: 
      uses: ./.github/workflows/complete_test_suite.yml

    Security:
      strategy:
        matrix:
          task: [""]
      name: Project Security Scan
      uses: ./.github/workflows/project_security_scan.yml

    Quality:
      strategy:
        matrix:
          task: [""]
      name: Code Quality Analysis
      needs: [Test, Security]
      uses: ./.github/workflows/code_quality_analysis.yml

    Format:
      strategy:
        matrix:
          task: [""]
      name: Code Format Check
      needs: [Test, Security]
      uses: ./.github/workflows/code_format_check.yml