name: Code Format Check

on:
  workflow_call:

jobs:
  code-style:
    name: Code Style Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install required packages
        run: python -m pip install pycodestyle==2.12.1

      - name: Check code style
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python -m pycodestyle --max-line-length=160 gherkin_processor/

  documentation-style:
    name: Documentation Style Check
    runs-on: ubuntu-latest
      
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install required packages
        run: python -m pip install pydocstyle==6.3.0
      
      - name: Check documentation style
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python -m pydocstyle gherkin_processor/
      