name: Code Format

on:
  workflow_call:

jobs:
  code-format:
    name: Code Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install required packages
        run: python -m pip install black==24.10.0

      - name: Check code format
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: black --check .

  code-style:
    name: Code Style Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install required packages
        run: python -m pip install pycodestyle==2.12.1

      - name: Check code style
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pycodestyle --max-line-length=160 .

  documentation-style:
    name: Documentation Style Check
    runs-on: ubuntu-latest
      
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
      
      - name: Install required packages
        run: python -m pip install pydocstyle==6.3.0
      
      - name: Check documentation style
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pydocstyle .
      