name: Core Functionality

on:
  workflow_call:

jobs:
  windows-minimum-test:
    name: Test - Windows (python 3.10)
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install required packages
        run: python -m pip install required packages==8.3.4 pytest-cov==6.0.0
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest --cov --cov-fail-under=80 tests/

  windows-latest-test:
    name: Test - Windows (python latest)
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up latest Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install required packages
        run: python -m pip install required packages==8.3.4 pytest-cov==6.0.0
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest --cov --cov-fail-under=80 tests/
        
  linux-minimum-test:
    name: Test - Linux (python 3.10)
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install required packages
        run: python -m pip install required packages==8.3.4 pytest-cov==6.0.0
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest --cov --cov-fail-under=80 tests/

  linux-latest-test:
    name: Test - Linux (python latest)
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up latest Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install required packages
        run: python -m pip install required packages==8.3.4 pytest-cov==6.0.0
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest --cov --cov-fail-under=80 tests/
        
  macos-minimum-test:
    name: Test - MacOS (python 3.10)
    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install required packages
        run: python -m pip install required packages==8.3.4 pytest-cov==6.0.0==8.3.4
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest --cov --cov-fail-under=80 tests/

  macos-latest-test:
    name: Test - MacOS (python latest)
    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up latest Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install required packages
        run: python -m pip install required packages==8.3.4 pytest-cov==6.0.0==8.3.4
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest --cov --cov-fail-under=80 tests/
