name: Code Quality

on:
  workflow_call:

jobs:
  lint-verificaition:
    name: Lint Verification
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Pylint
        run: python -m pip install pylint

      - name: Run lint verification with Pylint
        run: pylint --max-line-length=150 --fail-under=9.85 .

  type-check:
    name: Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Mypy
        run: python -m pip install mypy

      - name: Run type check with Mypy
        run: mypy --strict --disable-error-code "import-untyped" .

  code-metrics:
    name: Code Metrics
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Xenon
        run: python -m pip install xenon

      - name: Run code metrics with Xenon
        run: xenon --max-average B --max-absolute B --max-modules B .
 
  circular-reference:
    name: Circular Reference Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install PyCycle
        run: python -m pip install pycycle

      - name: Run circular reference check with PyCycle
        run: pycycle --here
