name: Code Quality

on:
  workflow_call:

jobs:
  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install required packages
        run: python -m pip install pylint==3.3.2

      - name: Check code linting
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pylint --max-line-length=160 --fail-under=9.85 gherkin_processor/

  type-check:
    name: Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install required packages
        run: python -m pip install mypy==1.13.0

      - name: Check code type hints
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: mypy --strict --ignore-missing-imports gherkin_processor/


  code-metrics:
    name: Code Metrics
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install required packages
        run: python -m pip install radon==6.0.1

      - name: Check cyclomatic complexity
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          radon cc --min B gherkin_processor

      - name: Check maintainability index
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          radon mi --min B gherkin_processor