name: Project Security

on:
  workflow_call:

jobs:
  code-security:
    name: Code Security
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install required packages
        run: python -m pip install bandit==1.8.0

      - name: Check code security
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: bandit --recursive gherkin_processor/
